rules:
  - start: "0:00"
    until: "80:00"
    every_seconds: 30
    items:
      - "Чекай миникарту: кто пропал? где сапы? есть ли варды?"
      - "Сколько врагов видно? Если больше 3 то можно смело толкать зеркально. Если меньше то толкай аккуратно, заставь стянуться врагов к тебе и выйди"
