timeline:
  - at: "0:00"
    items:
      - "Старт: стянуться на баунти врагов / стать под свою"

  - at: "5:00"
    items:
      - "Заколить сапа купить OBS + Sentry на линию + мид / купить самому"

  - at: "5:40"
    items:
      - "Заколить сапа идити в мид контролить руну / Выдвигаться на руну самому"

  - at: "6:00"
    items:
      - "Активная РУНА"

  - at: "7:00"
    items:
      - "Висдом"

  - at: "14:00"
    items:
      - "Висдом"

  - at: "20:00"
    items:
      - "ТЕРЗАТЕЛЬ"
