windows:
  - from: "0:30"
    to: "7:30"
    level: danger
    priority: 100
    text: "ВЫСОКИЙ РИСК ГАНГОВ: сапы или мидер часто смещаются — нужен вижен на гейт/подход к лайну, следи за миникартой,
    если вижена нет, нужно зачилиться под тавером или в лесу"

  - from: "3:50"
    to: "4:20"
    level: warn
    priority: 50
    text: "Окно водных рун: возможны первые ротации и ТП реакции"

  - from: "6:00"
    to: "7:30"
    level: danger
    priority: 110
    text: "РУНЫ / МУДРОСТЬ: ожидай ротации — если линия одна, стой ближе к таверу и под вижном"

  - from: "19:30"
    to: "20:30"
    level: warn
    priority: 60
    text: "Подготовка к Терзателю: сгруппироваться, вижн, возможный смок"
