windows:
  - from: "5:30"
    to: "7:30"
    level: danger
    priority: 100
    text: "ВЫСОКИЙ РИСК ГАНГОВ: сапы или мидер часто смещаются — нужен вижен на гейт/подход к лайну, следи за миникартой,
    если вижена нет, нужно зачилиться под тавером или в лесу"

  - from: "3:55"
    to: "4:10"
    level: warn
    priority: 50
    text: "Окно водных рун: возможны первые ротации, следи за картой"

  - from: "6:15"
    to: "7:30"
    level: warn
    priority: 110
    text: "РУНЫ / МУДРОСТЬ: ожидай ротации — если линия одна, стой ближе к таверу или под вижном"

  - from: "19:00"
    to: "20:00"
    level: warn
    priority: 60
    text: "Подготовка к Терзателю: заколить стягиваться в топ на торментора"

  - from: "20:00"
    to: "20:30"
    level: danger
    priority: 60
    text: "ТОРМЕНТОР. Заколить тиму забрать торма и быть готовым расталкать линии"
