hud:
  title: "Dota HUD"
  width: 549
  height: 400
  x: 30
  y: 30
  alpha: 0.80

ui:
  backend: "tk"

hotkeys:
  start: F8
  stop: F9
  reset: F10
  lock: F7

log_integration:
  enabled: false
  path: "C:/Program Files (x86)/Steam/steamapps/common/dota 2 beta/game/dota/console.log"
  start_patterns:
    - "GAME_IN_PROGRESS"
    - "DOTA_GAMERULES_STATE_GAME_IN_PROGRESS"
  poll_interval_ms: 100
  debounce_seconds: 8


timeline:
  - at: "0:00"
    items:
      - "Старт: блок кемпа / руна / расстановка по линиям"

  - at: "3:00"
    items:
      - "Водные руны (мид) — возможные первые ротации"

  - at: "4:00"
    items:
      - "Баунти руны — проверь реку, будь готов к файту"

  - at: "5:00"
    items:
      - "Покупка: OBS + Sentry / Dust + Quelling"

  - at: "5:40"
    items:
      - "Движение в мид: подготовка к руне (вижн, ТП)"

  - at: "6:00"
    items:
      - "Активная РУНА"

  - at: "7:00"
    items:
      - "АЛТАРЬ МУДРОСТИ"

  - at: "8:00"
    items:
      - "Баунти руны — контест с численным преимуществом"

  - at: "10:00"
    items:
      - "Лотос / объекты: давление на вышки, вижн"
      - "Ресет: потратить золото, принести варды, смоук"

  - at: "12:00"
    items:
      - "Баунти руны — ищи возможности на карте"

  - at: "14:00"
    items:
      - "АЛТАРЬ МУДРОСТИ"

  - at: "16:00"
    items:
      - "Баунти руны"

  - at: "20:00"
    items:
      - "ТЕРЗАТЕЛЬ"


rules:
  - start: "0:00"
    until: "20:00"
    every_seconds: 120
    items:
      - "Миникарта: кто пропал? где сапы? есть ли варды?"


windows:
  - from: "0:30"
    to: "7:30"
    level: danger
    priority: 100
    text: "ВЫСОКИЙ РИСК ГАНГОВ: сапы или мидер часто смещаются — нужен вижен на гейт/подход к лайну, следи за миникартой,
    если вижена нет, нужно зачилиться под тавером или в лесу"

  - from: "3:50"
    to: "4:20"
    level: warn
    priority: 50
    text: "Окно водных рун: возможны первые ротации и ТП реакции"

  - from: "6:00"
    to: "7:30"
    level: danger
    priority: 110
    text: "РУНЫ / МУДРОСТЬ: ожидай ротации — если линия одна, стой ближе к таверу и под вижном"

  - from: "19:30"
    to: "20:30"
    level: warn
    priority: 60
    text: "Подготовка к Терзателю: сгруппироваться, вижн, возможный смок"
