hud:
  title: "Dota HUD"
  width: 549
  height: 400
  x: 30
  y: 30
  alpha: 0.60
  font_family: "Radiance"
  font_size: 18
  font_weight: "bold"

hotkeys:
  lock: F7

macro_config: "macro.yaml"
modules:
  - "modules/timeline.yaml"
  - "modules/rules.yaml"
  - "modules/windows.yaml"

log_integration:
  enabled: false
  path: "C:/Program Files (x86)/Steam/steamapps/common/dota 2 beta/game/dota/console.log"
  start_patterns:
    - "GAME_IN_PROGRESS"
    - "DOTA_GAMERULES_STATE_GAME_IN_PROGRESS"
  poll_interval_ms: 100
  debounce_seconds: 8

